"""
OpenAPI 3.1.0 generator.

Converts a list of detected ApiCall objects into a valid OpenAPI 3.1.0
specification dictionary, which can then be serialised to JSON or YAML.

Merging logic
─────────────
• Multiple calls to the same (path, method) are merged into one operation.
• Parameters are deduplicated by (name, in).
• If conflicting values exist, the first one wins and a note is added.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional, Tuple

from ..models.api_call import ApiCall, ResolutionStatus

logger = logging.getLogger(__name__)


class OpenAPIGenerator:
    """Generates an OpenAPI 3.1.0 spec dict from a list of ApiCall objects."""

    def generate(
        self,
        api_calls: List[ApiCall],
        title: str = "Detected REST APIs",
        version: str = "1.0.0",
        description: str = "Auto-generated by ai-agents Java REST API Analyzer",
    ) -> Dict[str, Any]:
        """
        Build and return the full OpenAPI 3.1.0 document as a Python dict.

        Parameters
        ----------
        api_calls   : detected API calls (from one or more analyzers)
        title       : info.title value
        version     : info.version value
        description : info.description value
        """
        spec: Dict[str, Any] = {
            "openapi": "3.1.0",
            "info": {
                "title": title,
                "version": version,
                "description": description,
            },
            "paths": {},
        }

        for call in api_calls:
            path = call.url_template or call.url
            if not path:
                logger.warning("Skipping call with no path: %s", call)
                continue

            # Ensure the path starts with /
            if not path.startswith("/") and not path.startswith("http"):
                path = "/" + path

            method = call.method.lower()

            if path not in spec["paths"]:
                spec["paths"][path] = {}

            if method not in spec["paths"][path]:
                spec["paths"][path][method] = self._build_operation(call, path)
            else:
                # Merge into the existing operation
                self._merge_operation(spec["paths"][path][method], call)

        return spec

    def to_json(self, spec: Dict[str, Any], indent: int = 2) -> str:
        """Serialise the spec to a pretty-printed JSON string."""
        return json.dumps(spec, indent=indent, ensure_ascii=False)

    # ── Operation builders ────────────────────────────────────────────────────

    def _build_operation(self, call: ApiCall, path: str) -> Dict[str, Any]:
        """Create a fresh OpenAPI operation object from an ApiCall."""
        operation: Dict[str, Any] = {
            "summary": f"{call.method.upper()} {path}",
            "description": self._build_description(call),
            "parameters": self._build_parameters(call),
            "responses": {
                "200": {"description": "Successful response"},
                "4XX": {"description": "Client error"},
                "5XX": {"description": "Server error"},
            },
            # OpenAPI extension — preserves provenance for debugging
            "x-source": self._build_source_ext(call),
        }

        if call.body is not None:
            operation["requestBody"] = self._build_request_body(call)

        if call.notes:
            operation["x-analyzer-notes"] = call.notes

        return operation

    def _build_description(self, call: ApiCall) -> str:
        lines = [
            f"Detected in `{call.source_file}` at line {call.source_line}.",
            f"Library: `{call.library}`.",
        ]
        if call.resolution_status == ResolutionStatus.DYNAMIC:
            lines.append(
                "⚠️ URL was dynamically constructed — path parameters are inferred heuristically."
            )
        elif call.resolution_status == ResolutionStatus.LLM_RESOLVED:
            lines.append("ℹ️ URL was resolved with LLM assistance.")
        return "\n".join(lines)

    def _build_parameters(self, call: ApiCall) -> List[Dict[str, Any]]:
        params: List[Dict[str, Any]] = []
        seen: set[Tuple[str, str]] = set()

        def add(p: Dict[str, Any]) -> None:
            key = (p["name"], p["in"])
            if key not in seen:
                seen.add(key)
                params.append(p)

        # Path parameters
        for name in call.path_params:
            add({
                "name": name,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
            })

        # Query parameters
        for name, example in call.query_params.items():
            p: Dict[str, Any] = {
                "name": name,
                "in": "query",
                "required": False,
                "schema": {"type": "string"},
            }
            if example:
                p["example"] = example
            add(p)

        # Header parameters (exclude Content-Type / Accept — those go elsewhere)
        skip_headers = {"content-type", "accept"}
        for name, example in call.headers.items():
            if name.lower() in skip_headers:
                continue
            p = {
                "name": name,
                "in": "header",
                "required": False,
                "schema": {"type": "string"},
            }
            if example and not _looks_like_variable(example):
                p["example"] = example
            add(p)

        # Cookie parameters
        for name, example in call.cookies.items():
            p = {
                "name": name,
                "in": "cookie",
                "required": False,
                "schema": {"type": "string"},
            }
            if example and not _looks_like_variable(example):
                p["example"] = example
            add(p)

        return params

    def _build_request_body(self, call: ApiCall) -> Dict[str, Any]:
        content_type = call.body_content_type or "application/json"
        body_schema: Dict[str, Any] = {"type": "string"}

        media: Dict[str, Any] = {"schema": body_schema}
        if call.body and not _looks_like_variable(call.body):
            # Try to parse as JSON for a richer schema hint
            try:
                parsed = json.loads(call.body)
                if isinstance(parsed, dict):
                    body_schema = {
                        "type": "object",
                        "properties": {
                            k: {"type": _json_type(v)} for k, v in parsed.items()
                        },
                        "example": parsed,
                    }
                    media["schema"] = body_schema
                else:
                    media["example"] = call.body
            except (json.JSONDecodeError, TypeError):
                media["example"] = call.body

        return {
            "required": True,
            "content": {content_type: media},
        }

    def _build_source_ext(self, call: ApiCall) -> Dict[str, Any]:
        return {
            "file": call.source_file,
            "line": call.source_line,
            "library": call.library,
            "resolutionStatus": call.resolution_status.value,
        }

    # ── Merge logic ───────────────────────────────────────────────────────────

    def _merge_operation(
        self, existing: Dict[str, Any], call: ApiCall
    ) -> None:
        """Merge a duplicate (path, method) into an existing operation."""
        # Append extra source
        existing.setdefault("x-source", {}).setdefault("also-detected-in", []).append(
            {"file": call.source_file, "line": call.source_line}
        )
        # Add any new parameters
        existing_param_keys = {
            (p["name"], p["in"]) for p in existing.get("parameters", [])
        }
        for new_param in self._build_parameters(call):
            key = (new_param["name"], new_param["in"])
            if key not in existing_param_keys:
                existing.setdefault("parameters", []).append(new_param)
                existing_param_keys.add(key)

        if call.notes:
            existing.setdefault("x-analyzer-notes", []).extend(call.notes)


# ── Utilities ─────────────────────────────────────────────────────────────────

def _looks_like_variable(text: str) -> bool:
    """Return True if the string looks like a Java expression (not a literal)."""
    return any(c in text for c in ("(", ")", "+", ".", " ", "{"))


def _json_type(value: Any) -> str:
    """Map a Python value to an OpenAPI/JSON Schema type string."""
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "string"
